# Imports and load data

In [1]:
import sys
sys.path.append('/home/apoorva/Desktop/Work/olr')

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from scripts.utils.load import load_pca_anomaly
from sklearn.metrics import classification_report, confusion_matrix

2024-05-25 04:16:30.108217: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
pca_x, olr_labels = load_pca_anomaly()

In [3]:
pca_x.shape, olr_labels.shape

((5920, 5920), (40, 134))

In [5]:
def pentad_data(count):
    '''
    count is 0-indexed
    count = 0 corresponds to first leading pentad
    count = 1 corresponds to second leading pentad
    count = 2 corresponds to third leading pentad
    '''
    global olr_labels, pca_x
    assert count == 0 or count == 1 or count == 2
    pca_x_50 = pca_x[:, :50]
    pca_x_50 = np.array([pca_x_50[i*40+j:i*40+j+15, :] for i in range(40) for j in range(134 - (5*count))])
    labels = np.reshape(np.reshape(olr_labels, (40, 134))[:, (5*count):], (-1))
    X_train, X_test, y_train, y_test = train_test_split(pca_x_50, labels, random_state=1337, train_size=0.875, stratify=labels)
    return X_train, X_test, y_train, y_test

# Model Training: Conv1D

## First Pentad

In [6]:
X_train, X_test, y_train, y_test = pentad_data(0)

In [7]:
y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

In [8]:
inputs = keras.layers.Input(shape=(15, 50))
x = layers.SeparableConv1D(filters=32, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           )(inputs)
x = layers.BatchNormalization()(x)
x = keras.layers.SeparableConv1D(filters=16, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5)
                           )(x)
x = layers.BatchNormalization()(x)
x = layers.SeparableConv1D(filters=8, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           )(x)
x = layers.BatchNormalization()(x)
x = layers.Flatten()(x)
# x = layers.Dropout(0.3)(x)
x = keras.layers.Dense(10, activation=keras.layers.LeakyReLU())(x)
x = keras.layers.Dense(3, name='logits')(x)
output = layers.Activation('softmax')(x)

pred_model = keras.Model(inputs=inputs, outputs=output)
pred_model.summary()

LEARNING_RATE=9.19e-3
EPOCHS=100

pred_model.compile(
                loss=keras.losses.CategoricalFocalCrossentropy(alpha=0.3, gamma=0.5),
                # optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
                optimizer=keras.optimizers.SGD(learning_rate=LEARNING_RATE, momentum=0.9, nesterov=True),
                metrics=[
                    keras.metrics.F1Score(average='macro'),
                    keras.metrics.CategoricalAccuracy(),
                ],
            )

# scheduler = keras.optimizers.schedules.CosineDecay(initial_learning_rate=LEARNING_RATE, decay_steps=EPOCHS, alpha=2e-3)
# callbacks=[
#             keras.callbacks.EarlyStopping(patience=10, monitor='val_f1_score', mode='max', start_from_epoch=50, restore_best_weights=True),
#             # keras.callbacks.LearningRateScheduler(schedule=scheduler),
#         ]

pred_model.fit(X_train, y_train_onehot,
            batch_size=16,
            epochs=EPOCHS,
            validation_split=0.2)#,
            # callbacks=callbacks)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 15, 50)]          0         
                                                                 
 separable_conv1d (Separabl  (None, 13, 32)            1782      
 eConv1D)                                                        
                                                                 
 batch_normalization (Batch  (None, 13, 32)            128       
 Normalization)                                                  
                                                                 
 separable_conv1d_1 (Separa  (None, 11, 16)            624       
 bleConv1D)                                                      
                                                                 
 batch_normalization_1 (Bat  (None, 11, 16)            64        
 chNormalization)                                            

In [9]:
y_pred = pred_model.predict(X_train)

y_pred = np.argmax(y_pred, axis=1)

print("Training")
print(confusion_matrix(y_pred=y_pred, y_true=y_train))
print(classification_report(y_pred=y_pred, y_true=y_train))

y_pred = pred_model.predict(X_test)

y_pred = np.argmax(y_pred, axis=1)

print("Testing")
print(confusion_matrix(y_pred=y_pred, y_true=y_test))
print(classification_report(y_pred=y_pred, y_true=y_test))

147/147 [==============================] - 0s 807us/step
Training
[[ 272  306   36]
 [ 215 2876  310]
 [  65  306  304]]
              precision    recall  f1-score   support

         0.0       0.49      0.44      0.47       614
         1.0       0.82      0.85      0.83      3401
         2.0       0.47      0.45      0.46       675

    accuracy                           0.74      4690
   macro avg       0.59      0.58      0.59      4690
weighted avg       0.73      0.74      0.73      4690

21/21 [==============================] - 0s 829us/step
Testing
[[ 16  64   8]
 [ 53 369  64]
 [ 12  66  18]]
              precision    recall  f1-score   support

         0.0       0.20      0.18      0.19        88
         1.0       0.74      0.76      0.75       486
         2.0       0.20      0.19      0.19        96

    accuracy                           0.60       670
   macro avg       0.38      0.38      0.38       670
weighted avg       0.59      0.60      0.60       670



## Second Pentad

In [10]:
X_train, X_test, y_train, y_test = pentad_data(1)

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

In [11]:
inputs = keras.layers.Input(shape=(15, 50))
x = layers.SeparableConv1D(filters=32, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           )(inputs)
x = layers.BatchNormalization()(x)
x = keras.layers.SeparableConv1D(filters=16, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5)
                           )(x)
x = layers.BatchNormalization()(x)
x = layers.SeparableConv1D(filters=8, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           )(x)
x = layers.BatchNormalization()(x)
x = layers.Flatten()(x)
# x = layers.Dropout(0.3)(x)
x = keras.layers.Dense(10, activation=keras.layers.LeakyReLU())(x)
x = keras.layers.Dense(3, name='logits')(x)
output = layers.Activation('softmax')(x)

pred_model = keras.Model(inputs=inputs, outputs=output)
pred_model.summary()

LEARNING_RATE=9.2e-3
EPOCHS=85

pred_model.compile(
                loss=keras.losses.CategoricalFocalCrossentropy(alpha=0.15, gamma=0.5),
                # optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
                optimizer=keras.optimizers.SGD(learning_rate=LEARNING_RATE, momentum=0.9, nesterov=True),
                metrics=[
                    keras.metrics.F1Score(average='macro'),
                    keras.metrics.CategoricalAccuracy(),
                ],
            )

# scheduler = keras.optimizers.schedules.CosineDecay(initial_learning_rate=LEARNING_RATE, decay_steps=EPOCHS, alpha=2e-3)
# callbacks=[
#             keras.callbacks.EarlyStopping(patience=10, monitor='val_f1_score', mode='max', start_from_epoch=50, restore_best_weights=True),
#             # keras.callbacks.LearningRateScheduler(schedule=scheduler),
#         ]

pred_model.fit(X_train, y_train_onehot,
            batch_size=16,
            epochs=EPOCHS,
            validation_split=0.2)#,
            # callbacks=callbacks)

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 15, 50)]          0         
                                                                 
 separable_conv1d_3 (Separa  (None, 13, 32)            1782      
 bleConv1D)                                                      
                                                                 
 batch_normalization_3 (Bat  (None, 13, 32)            128       
 chNormalization)                                                
                                                                 
 separable_conv1d_4 (Separa  (None, 11, 16)            624       
 bleConv1D)                                                      
                                                                 
 batch_normalization_4 (Bat  (None, 11, 16)            64        
 chNormalization)                                          

In [12]:
y_pred = pred_model.predict(X_train)
y_pred = np.argmax(y_pred, axis=1)

print("Training")
print(confusion_matrix(y_pred=y_pred, y_true=y_train))
print(classification_report(y_pred=y_pred, y_true=y_train))


y_pred = pred_model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

print("Testing")
print(confusion_matrix(y_pred=y_pred, y_true=y_test))
print(classification_report(y_pred=y_pred, y_true=y_test))

142/142 [==============================] - 0s 761us/step
Training
[[ 217  338   35]
 [ 129 2936  185]
 [  48  386  241]]
              precision    recall  f1-score   support

         0.0       0.55      0.37      0.44       590
         1.0       0.80      0.90      0.85      3250
         2.0       0.52      0.36      0.42       675

    accuracy                           0.75      4515
   macro avg       0.63      0.54      0.57      4515
weighted avg       0.73      0.75      0.73      4515

21/21 [==============================] - 0s 788us/step
Testing
[[ 16  60   8]
 [ 36 384  45]
 [  6  69  21]]
              precision    recall  f1-score   support

         0.0       0.28      0.19      0.23        84
         1.0       0.75      0.83      0.79       465
         2.0       0.28      0.22      0.25        96

    accuracy                           0.65       645
   macro avg       0.44      0.41      0.42       645
weighted avg       0.62      0.65      0.63       645



## Third Pentad

In [13]:
X_train, X_test, y_train, y_test = pentad_data(2)

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

In [14]:
inputs = keras.layers.Input(shape=(15, 50))
x = layers.SeparableConv1D(filters=32, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           )(inputs)
x = layers.BatchNormalization()(x)
x = keras.layers.SeparableConv1D(filters=16, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5)
                           )(x)
x = layers.BatchNormalization()(x)
x = layers.SeparableConv1D(filters=8, kernel_size=3, 
                           activation=keras.layers.ELU(),
                           depthwise_initializer=keras.initializers.GlorotNormal(),
                           pointwise_initializer=keras.initializers.GlorotNormal(),
                           depthwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           pointwise_regularizer=keras.regularizers.L1L2(l1=1e-5, l2=1e-5),
                           )(x)
x = layers.BatchNormalization()(x)
x = layers.Flatten()(x)
# x = layers.Dropout(0.3)(x)
x = keras.layers.Dense(10, activation=keras.layers.LeakyReLU())(x)
x = keras.layers.Dense(3, name='logits')(x)
output = layers.Activation('softmax')(x)

pred_model = keras.Model(inputs=inputs, outputs=output)
pred_model.summary()

LEARNING_RATE=9.2e-3
EPOCHS=85

pred_model.compile(
                loss=keras.losses.CategoricalFocalCrossentropy(alpha=0.15, gamma=0.5),
                # optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
                optimizer=keras.optimizers.SGD(learning_rate=LEARNING_RATE, momentum=0.9, nesterov=True),
                metrics=[
                    keras.metrics.F1Score(average='macro'),
                    keras.metrics.CategoricalAccuracy(),
                ],
            )

# scheduler = keras.optimizers.schedules.CosineDecay(initial_learning_rate=LEARNING_RATE, decay_steps=EPOCHS, alpha=2e-3)
# callbacks=[
#             keras.callbacks.EarlyStopping(patience=10, monitor='val_f1_score', mode='max', start_from_epoch=50, restore_best_weights=True),
#             # keras.callbacks.LearningRateScheduler(schedule=scheduler),
#         ]

pred_model.fit(X_train, y_train_onehot,
            batch_size=16,
            epochs=EPOCHS,
            validation_split=0.2)#,
            # callbacks=callbacks)

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 15, 50)]          0         
                                                                 
 separable_conv1d_6 (Separa  (None, 13, 32)            1782      
 bleConv1D)                                                      
                                                                 
 batch_normalization_6 (Bat  (None, 13, 32)            128       
 chNormalization)                                                
                                                                 
 separable_conv1d_7 (Separa  (None, 11, 16)            624       
 bleConv1D)                                                      
                                                                 
 batch_normalization_7 (Bat  (None, 11, 16)            64        
 chNormalization)                                          

In [15]:
y_pred = pred_model.predict(X_train)

y_pred = np.argmax(y_pred, axis=1)

print("Training")
print(confusion_matrix(y_pred=y_pred, y_true=y_train))
print(classification_report(y_pred=y_pred, y_true=y_train))

y_pred = pred_model.predict(X_test)

y_pred = np.argmax(y_pred, axis=1)

print("Testing")
print(confusion_matrix(y_pred=y_pred, y_true=y_test))
print(classification_report(y_pred=y_pred, y_true=y_test))

136/136 [==============================] - 0s 835us/step
Training
[[ 210  310   48]
 [ 140 2770  187]
 [  40  377  258]]
              precision    recall  f1-score   support

         0.0       0.54      0.37      0.44       568
         1.0       0.80      0.89      0.85      3097
         2.0       0.52      0.38      0.44       675

    accuracy                           0.75      4340
   macro avg       0.62      0.55      0.58      4340
weighted avg       0.72      0.75      0.73      4340

20/20 [==============================] - 0s 811us/step
Testing
[[ 21  56   4]
 [ 45 352  46]
 [  6  74  16]]
              precision    recall  f1-score   support

         0.0       0.29      0.26      0.27        81
         1.0       0.73      0.79      0.76       443
         2.0       0.24      0.17      0.20        96

    accuracy                           0.63       620
   macro avg       0.42      0.41      0.41       620
weighted avg       0.60      0.63      0.61       620



# WandB Sweep

To pick the best possible params for the Conv-1D model, since randomly trying params wasn't fruitful.

In [ ]:
import datetime
import os
import wandb

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils import to_categorical
from wandb.keras import WandbCallback, WandbMetricsLogger

EPOCHS = 100
LEARNING_RATE = 1e-2
MOMENTUM = 0.9
X_train_50 = None
y_train_onehot = None

def def_model():
    inputs = keras.Input(shape=(750,))
    x = layers.Reshape((15, 50))(inputs)
    x = layers.SeparableConv1D(filters=32, kernel_size=3, 
                            activation=keras.layers.ELU(),
                            depthwise_initializer=keras.initializers.GlorotNormal(),
                            pointwise_initializer=keras.initializers.GlorotNormal())(x)
    x = layers.BatchNormalization()(x)
    x = keras.layers.SeparableConv1D(filters=16, kernel_size=3, 
                            activation=keras.layers.ELU(),
                            depthwise_initializer=keras.initializers.GlorotNormal(),
                            pointwise_initializer=keras.initializers.GlorotNormal())(x)
    x = layers.BatchNormalization()(x)
    x = layers.SeparableConv1D(filters=8, kernel_size=3, 
                            activation=keras.layers.ELU(),
                            depthwise_initializer=keras.initializers.GlorotNormal(),
                            pointwise_initializer=keras.initializers.GlorotNormal())(x)
    x = layers.BatchNormalization()(x)
    x = layers.Flatten()(x)
    x = layers.Dense(10, activation=keras.layers.LeakyReLU(),
                    kernel_initializer=keras.initializers.GlorotNormal(),
                    bias_initializer=keras.initializers.Zeros())(x)
    x = layers.BatchNormalization()(x)
    outputs = layers.Dense(3, activation="softmax")(x)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model


def get_data():
    global X_train_50, y_train_onehot
    pca_x, olr_labels = load_pca_anomaly()
    pca_x_50 = pca_x[:, :50]
    pca_x_50 = np.array([pca_x_50[i*40+j:i*40+j+15, :] for j in range(135) for i in range(40)])
    olr_labels = np.reshape(olr_labels, -1)
    X_train, _, y_train, _ = train_test_split(pca_x_50, olr_labels, random_state=1337, train_size=0.875, stratify=olr_labels)
    X_train_50 = np.reshape(X_train, (4725, -1))
    y_train_onehot = to_categorical(y_train)


def get_optimizer(lr=1e-3, optimizer="adam"):
    if optimizer.lower() == "adam":
        return keras.optimizers.Adam(learning_rate=lr)
    if optimizer.lower() == "sgd":
        return keras.optimizers.SGD(learning_rate=lr, momentum=0.9)
    if optimizer.lower() == "nesterov":
        return keras.optimizers.SGD(learning_rate=lr, momentum=0.9, nesterov=True)
    if optimizer.lower() == "rmsprop":
        return keras.optimizers.RMSprop(earning_rate=lr, momentum=0.9)


def train(model, batch_size=64, epochs=10, lr=1e-3, optimizer='rmsprop', alpha=0.25, gamma=2, log_freq=10):
    global X_train_50, y_train_onehot
    tf.keras.backend.clear_session()
    model.compile(loss=keras.losses.CategoricalFocalCrossentropy(alpha=alpha, gamma=gamma), 
                  optimizer=get_optimizer(lr, optimizer), 
                  metrics=  [
                                keras.metrics.F1Score(average='macro'),
                                keras.metrics.CategoricalAccuracy(),
                            ])
    TIMESTAMP = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    mydir = os.path.join(os.getcwd(), f"logs/logdir_{TIMESTAMP}")
    os.makedirs(mydir)
    callbacks=[
                keras.callbacks.TensorBoard(log_dir=mydir),
                WandbCallback(log_gradients=True, training_data=(X_train_50, y_train_onehot)),
                WandbMetricsLogger(log_freq=log_freq)
            ]

    model.fit(X_train, 
              y_train_onehot, 
              batch_size=batch_size, 
              epochs=epochs, 
              validation_split=0.1, 
              callbacks=callbacks)
    

def sweep_train(config_defaults=None):
    with wandb.init(config=config_defaults):
        wandb.config.architecture_name = "Conv-1D"
        wandb.config.dataset_name = "OLR"

        model = def_model()

        train(model, 
              wandb.config.batch_size, 
              wandb.config.epochs,
              wandb.config.lr,
              wandb.config.optimizer,
              wandb.config.alpha,
              wandb.config.gamma)


if __name__ == '__main__':
    get_data()
    wandb.login()
    sweep_configuration = {
        "method": "random",
        "name": "sweep_rms",
        "metric":   {
                        "goal": "maximize", 
                        "name": "val_f1_score"
                    },  
        "parameters":   {
                            "batch_size":   {
                                                "values": [8, 16, 32, 64, 128]
                                            },
                            "epochs":   {
                                            "distribution": "int_uniform",
                                            "max": 400,
                                            "min": 15
                                        },
                            "lr":   {
                                        "distribution": "uniform",
                                        "max": 1e-2, 
                                        "min": 1e-6
                                    },
                            "optimizer":    {
                                                "values": ["sgd", "nesterov", "adam", "rmsprop"],
                                            },
                            "alpha":{
                                        "values": [0.1, 0.15, 0.2, 0.25, 0.3, 0.35]
                                    },
                            "gamma":{
                                        "values": [0.5, 1, 2, 3, 4, 5]
                                    },
                        },
    }
    sweep_id = wandb.sweep(sweep=sweep_configuration, project="OLR_Base_Model")
    wandb.agent(sweep_id, function=sweep_train, count=50)